package fi.lipp.blog.model.exceptions

class UserNotFoundException : Exception()
